import { FlaskConical, Sparkles } from 'lucide-react';
import type { AiSource } from '../domain/aiTypes';
import { Pill } from './ui';

/** Marks anything the AI produced. In demo mode (no API key) it says so, so sample data is never mistaken for a real reading. */
export function AiBadge({ source = 'ai' }: { source?: AiSource }) {
  if (source === 'demo')
    return (
      <Pill tone="amber" title="No API key is configured, so this is sample data, not a real AI answer">
        <FlaskConical className="h-3 w-3" aria-hidden /> Demo data
      </Pill>
    );
  return (
    <Pill tone="purple" title="Generated by AI. Please check it before relying on it.">
      <Sparkles className="h-3 w-3" aria-hidden /> AI
    </Pill>
  );
}
