// Bundles the AI server into the single file Vercel runs as a serverless function: api/ai/[...path].js
// Run `npm run build:api` after changing anything in server/. The result is committed on purpose, so Vercel
// finds the function without needing a build step for it. Packages (like @google/genai) stay external and are
// installed by Vercel from package.json; only our own code is bundled.

import { mkdirSync } from 'node:fs';
import { build } from 'esbuild';

mkdirSync('api/ai', { recursive: true });
await build({
  entryPoints: ['server/vercelHandler.ts'],
  outfile: 'api/ai/[...path].js',
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  packages: 'external',
  banner: { js: '// GENERATED by scripts/buildApi.mjs from server/. Do not edit by hand.' },
  logLevel: 'info',
});
